### ISSUE TITLE
Typoscript condition for preview and email doesn't work with routeEnhancers

### ISSUE THREAD

**Issue by FLeudts** [in2code-de/luxletter#235]
When I set a PageTypeSuffix for the type 1562349004 I had to add this typoscript condition.

`request && request.getPageArguments()?.getPageType() == 1562349004` 
 
Otherwise the lib.contentElement Paths didn't get updated. 

`request && traverse(request.getQueryParams(), 'type') == 1562349004`

The existing condition didn't work.

I found the condition here [Typo3 Documentation](https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Conditions/Index.html#condition-function-request-getpagearguments)  and in the existing example for the getQueryParams function [Typo3 Documentation](https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Conditions/Index.html#condition-function-request-getqueryparams) the example does show that the path isn't converted to route parts.

**Comment by einpraegsam** [comment]
Can you please paste your complete TypoScript here and write down what's not working and what`s changing if you add your own TypoScript?

**Comment by FLeudts** [comment]
```

[request && traverse(request.getQueryParams(), 'type') == 1562349004]
lib {
  contentElement {
    templateRootPaths {
      100 = EXT:luxletter/Resources/Private/FluidStyledMailContent/Templates/
    }

    partialRootPaths {
      100 = EXT:luxletter/Resources/Private/FluidStyledMailContent/Partials/
    }

    layoutRootPaths {
      100 = EXT:luxletter/Resources/Private/FluidStyledMailContent/Layouts/
    }
  }
}

// Settings for EXT:news
tt_content {
  news_pi1.templateName = NewsList
  news_newsliststicky.templateName = NewsList
  news_newsselectedlist.templateName = NewsList
}
plugin.tx_news {
  view {
    templateRootPaths {
      10 = EXT:luxletter/Resources/Private/FluidStyledMailContent/Templates/
    }
    layoutRootPaths {
      10 = EXT:luxletter/Resources/Private/FluidStyledMailContent/Layouts/
    }
  }
}
[end]
```

This is the code from FluidStyledMailContent which doesn't work


I had to add this for the rendering to work again
```

[request && request.getPageArguments()?.getPageType() == 1562349004]
lib {
    contentElement {
        templateRootPaths {
            10 = EXT:luxletter/Resources/Private/FluidStyledMailContent/Templates/
        }
        partialRootPaths {
            10 = EXT:luxletter/Resources/Private/FluidStyledMailContent/Partials/
        }
        layoutRootPaths {
            10 = EXT:luxletter/Resources/Private/FluidStyledMailContent/Layouts/
        }
    }
}
[end]
```

**Comment by einpraegsam** [comment]
I just tested locally with TYPO3 13.4.8.
Opening frontend with an URL like https://local.luxletter.de/newsletter2020-1?type=1562349004 will render textmedia table based. What do I miss here?

**Comment by FLeudts** [comment]
In my installation I have the routeEnhancers set which is why there is no ?type=1562349004 at the end of the url. Then the condition doesn't work.

**Comment by einpraegsam** [comment]
Thx, I missed that

But I still cannot see a problem with this URL now:
`https://local.luxletter.de/newsletter2020-1/digital`

My Route configuration looks like:
```
base: 'https://%env(HOST)%/'
errorHandling: {  }
languages:
  -
    title: deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE
    iso-639-1: de
    websiteTitle: Lux
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ''
    fallbackType: strict
    fallbacks: ''
    flag: de
    languageId: '0'
luxletterUnsubscribePid: '6'
rootPageId: 1
routes: {  }
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: /
    index: ''
    suffix: /
    map:
      preview: 1560777975
      digital: 1562349004
      pixel: 1561894816
websiteTitle: ''
```
