### ISSUE TITLE
site:configuration with base variants saving/dispatch error

### ISSUE THREAD

**Issue by ses2013** [in2code-de/luxletter#86]
Save/Dispatch throws error:
"Call to a member function getSiteConfiguration() on null"
Line 409
$newsletter['bodytext'] = $parseService->getParsedContent($configuration->getSiteConfiguration());

Also Testmail won't send.
Preview looks fine though.

I have followed ALL "breaking changes" for version 4.0.0.
Site configuration uses baseVariants for Development Context.
I have also tried to set the "base" of the language to the full Domain.

Here is my Site Configuration:

```
base: 'https://www.domain.de/'
baseVariants:
  -
    base: 'https://dev.domain.de/'
    condition: 'applicationContext == "Development"'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=5'
  -
    errorCode: 403
    errorHandler: Page
    errorContentSource: 't3://page?uid=5'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: ''
    hreflang: en-US
    direction: ''
    flag: us
    websiteTitle: ''
luxletterUnsubscribePid: '344'
rootPageId: 1
routes:
  -
    route: sitemap.xml
    type: uri
    source: 't3://page?uid=1&type=1533906435'
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /typo3_src/\r\nAllow: /typo3/sysext/frontend/Resources/Public/*\r\nDisallow: /typo3conf/\r\nDisallow: /fileadmin/application-submission/\r\n"
websiteTitle: ''
imports:
  -
    resource: 'EXT:calendarize/Configuration/Yaml/RouteEnhancers.yaml'
```
